namespace HospitioApi.Core.HandleCustomerGuestAppEnhanceYourStayCategoryItemsExtra.Commands.DeleteCustomerGuestAppEnhanceYourStayCategoryItemExtra;

public class DeleteCustomerGuestAppEnhanceYourStayCategoryItemExtraIn
{
    public int CustomerGuestAppEnhanceYourStayItemId { get; set; }
}