using MediatR;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using HospitioApi.Core.Options;
using HospitioApi.Core.Services.HandlerResponse;
using HospitioApi.Data;
using HospitioApi.Data.Models;
using HospitioApi.Shared;
using HospitioApi.Shared.Enums;
using System.Text;

namespace HospitioApi.Core.HandleCustomers.Commands.ERPCustomerActivation
{
	public record ERPCustomerActivationRequest(ERPCustomerActivationIn In) : IRequest<AppHandlerResponse>;

	public class ERPCustomerActivationHandler : IRequestHandler<ERPCustomerActivationRequest, AppHandlerResponse>
	{
		private readonly ApplicationDbContext _db;
		private readonly IHandlerResponseFactory _response;
		private readonly MiddlewareApiSettingsOptions _middlewareApiSettingsOptions;

		public ERPCustomerActivationHandler(ApplicationDbContext db, IHandlerResponseFactory response, IOptions<MiddlewareApiSettingsOptions> middlewareApiSettingsOptions)
		{
			_db = db;
			_response = response;
			_middlewareApiSettingsOptions = middlewareApiSettingsOptions.Value;
		}
		public async Task<AppHandlerResponse> Handle(ERPCustomerActivationRequest request, CancellationToken cancellationToken)
		{
			if (request.In.CustomerStatus != CustomerActivationStatus.Activate.ToString() && request.In.CustomerStatus != CustomerActivationStatus.Deactivate.ToString())
			{
				return _response.Error("Invalid Customer Status. The 'CustomerStatus' field must be either 'Activate' or 'Deactivate'. Please provide a valid value.", AppStatusCodeError.Gone410);
			}
			if (!Guid.TryParse(request.In.PylonUniqueCustomerId, out Guid guidResult))
			{
				return _response.Error($"Invalid Centurian ID. Please provide a valid GUID.", AppStatusCodeError.Conflict409);
			}
			string? UserUniqueId = null;
			Customer customer = await _db.Customers.Where(e => e.Guid == Guid.Parse(request.In.PylonUniqueCustomerId)).FirstOrDefaultAsync(cancellationToken);
			if (customer == null)
			{
				return _response.Error($"Customer with GuId {request.In.PylonUniqueCustomerId} could not be found.", AppStatusCodeError.Gone410);
			}
			if (customer.IsPylonGenerated == null)
			{
				return _response.Error($"Customer with GuId {request.In.PylonUniqueCustomerId} is not generated by Pyloan.", AppStatusCodeError.Gone410);
			}

			#region middleware
			try
			{
				using var client = new HttpClient();

				string firstApiUrl = _middlewareApiSettingsOptions.BaseUrl + "api/ChannelManager/token";

				var requestBody = new
				{
					username = _middlewareApiSettingsOptions.UserName,
					password = _middlewareApiSettingsOptions.Password,
				};

				var requestBodyJson = JsonConvert.SerializeObject(requestBody);
				var requestContent = new StringContent(requestBodyJson, Encoding.UTF8, "application/json");

				// Send a POST request to obtain the token
				var response = await client.PostAsync(firstApiUrl, requestContent);

				string? token = null;
				if (response.IsSuccessStatusCode)
				{
					// Read the token from the response
					var responseContent = await response.Content.ReadAsStringAsync();
					var responseObject = JObject.Parse(responseContent);

					if (responseObject != null && responseObject["token"] != null)
					{
						token = responseObject["token"].Value<string>();
					}
				}

				if (!string.IsNullOrEmpty(token))
				{
					HttpClient httpClient = new HttpClient();
					string middlewareApiUrl = _middlewareApiSettingsOptions.BaseUrl + "api/ChannelManager/users";
					httpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {token}");
					byte? GuidType = customer.GuidType ?? 2;
					var middlewareRequestBody = new
					{
						userCode = customer.Guid,
						hasGeaPlatform = request.In.CustomerStatus == CustomerActivationStatus.Activate.ToString() ? true : false
					};

					var middlewareRequestBodyJson = JsonConvert.SerializeObject(middlewareRequestBody);
					requestContent = new StringContent(middlewareRequestBodyJson, Encoding.UTF8, "application/json");

					response = await httpClient.PostAsync(middlewareApiUrl, requestContent);

					if (response.IsSuccessStatusCode)
					{
						var result = await response.Content.ReadAsStringAsync();
					}
				}
			}
			catch (HttpRequestException ex)
			{
				return _response.Error("An HTTP error occurred when call a Middleware APIS. " + ex.Message, AppStatusCodeError.InternalServerError500);
			}
			catch (JsonException ex)
			{
				return _response.Error("A JSON error occurred when call a Middleware APIS. " + ex.Message, AppStatusCodeError.InternalServerError500);
			}
			catch (Exception ex)
			{
				return _response.Error("Error occurred when call a Middleware APIS. " + ex.Message, AppStatusCodeError.InternalServerError500);
			}
			#endregion

			UserUniqueId = customer.Guid.ToString();
			if (request.In.CustomerStatus == CustomerActivationStatus.Activate.ToString())
			{
				customer.IsActive = true;
			}
			else
			{
				customer.IsActive = false;
			}
			await _db.SaveChangesAsync(cancellationToken);
			var UpdatedERPServicePackOut = new ERPCustomerstatusOut()
			{
				PylonUniqueCustomerId = UserUniqueId,
				CustomerStatus = customer.IsActive
			};
			return _response.Success(new ERPCustomerActivationOut($"Customer with UniqueId : {UserUniqueId} has been {(request.In.CustomerStatus == CustomerActivationStatus.Activate.ToString() ? "activated" : "deactivated")} successfully.", UpdatedERPServicePackOut));
		}
	}
}
