using MediatR;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using HospitioApi.Core.Options;
using HospitioApi.Core.Services.Common;
using HospitioApi.Core.Services.HandlerResponse;
using HospitioApi.Data;
using HospitioApi.Data.Models;
using HospitioApi.Shared;
using HospitioApi.Shared.Enums;
using System.Text;


namespace HospitioApi.Core.HandleCustomers.Commands.UpdateERPServicePack
{
    public record UpdateERPServicePackRequest(UpdateERPServicePackIn In) : IRequest<AppHandlerResponse>;
    public class UpdateERPServicePackHandler : IRequestHandler<UpdateERPServicePackRequest, AppHandlerResponse>
    {
        private readonly ApplicationDbContext _db;
        private readonly IHandlerResponseFactory _response;
        private readonly ICommonDataBaseOprationService _commonRepository;
        private readonly MiddlewareApiSettingsOptions _middlewareApiSettingsOptions;
        private readonly ILogger<UpdateERPServicePackHandler> _logger;


        public UpdateERPServicePackHandler(ApplicationDbContext db, IHandlerResponseFactory response, ICommonDataBaseOprationService commonRepository, IOptions<MiddlewareApiSettingsOptions> middlewareApiSettingsOptions, ILogger<UpdateERPServicePackHandler> logger)
        {
            _db = db;
            _response = response;
            _commonRepository = commonRepository;
            _middlewareApiSettingsOptions = middlewareApiSettingsOptions.Value;
            _logger = logger;
        }
        public async Task<AppHandlerResponse> Handle(UpdateERPServicePackRequest request, CancellationToken cancellationToken)
        {
            if (request.In.PurchaseType != ServicePackPurchaseType.Renew.ToString() && request.In.PurchaseType != ServicePackPurchaseType.Upgrade.ToString())
            {
                return _response.Error("Invalid Purchase Type. The 'PurchaseType' field must be either 'Renew' or 'Upgrade'. Please provide a valid value.", AppStatusCodeError.Gone410);
            }
            if (!Guid.TryParse(request.In.PylonUniqueCustomerId, out Guid guidResult))
            {
                return _response.Error($"Invalid PylonCustomer ID. Please provide a valid GUID.", AppStatusCodeError.Conflict409);
            }
            string? UserUniqueId = null;

            var eRPCustomer = new UpdateERPCustomer();

            Customer customer = await _db.Customers.Where(e => e.Guid == Guid.Parse(request.In.PylonUniqueCustomerId)).FirstOrDefaultAsync(cancellationToken);

            if (customer == null)
            {
                return _response.Error($"Customer with GuId {request.In.PylonUniqueCustomerId} could not be found.", AppStatusCodeError.Gone410);
            }
            if (customer.IsPylonGenerated == null)
            {
                return _response.Error($"Customer with GuId {request.In.PylonUniqueCustomerId} is not generated by Pyloan.", AppStatusCodeError.Gone410);
            }

            var previousCustomerProduct = await _db.Products.Where(e => e.Id == customer.ProductId).FirstOrDefaultAsync(cancellationToken);

            var upgradedCustomerProduct = await _db.Products.Where(e => e.Name == request.In.ServicePack).FirstOrDefaultAsync(cancellationToken);
            if (upgradedCustomerProduct == null)
            {
                return _response.Error($"Service Pack {request.In.ServicePack} could not be found.", AppStatusCodeError.Gone410);
            }
            if (request.In.PurchaseType == ServicePackPurchaseType.Upgrade.ToString())
            {
                if(previousCustomerProduct.Id == upgradedCustomerProduct.Id)
                {
                    return _response.Error($"You cannot Upgrade to the same service pack. Please select a different one.", AppStatusCodeError.Gone410);
                }
            }
            else
            {
                if (previousCustomerProduct.Id != upgradedCustomerProduct.Id)
                {
                    return _response.Error($"To Renew your service, you must choose the same service pack. Please select the correct one.", AppStatusCodeError.Gone410);
                }
            }
            if (upgradedCustomerProduct.IsActive != null && (bool)!upgradedCustomerProduct.IsActive)
            {
                upgradedCustomerProduct.IsActive = true;
                await _db.SaveChangesAsync(cancellationToken);
            }

            eRPCustomer.ServicePackId = upgradedCustomerProduct.Id;
            eRPCustomer.ExpirationInDay = request.In.ExpirationInDay;
            try
            {
                Customer serviceUpdatedCustomer = await _commonRepository.ERPCustomerServiceUpdate(eRPCustomer, customer, _db, cancellationToken);
                if (serviceUpdatedCustomer != null)
                {
                    UserUniqueId = serviceUpdatedCustomer.Guid.ToString();
                    var PropertyInfoData = await _db.CustomerPropertyInformations.Where(i => i.CustomerId == serviceUpdatedCustomer.Id).ToListAsync();
                    if (PropertyInfoData != null || PropertyInfoData!.Count > 0)
                    {

                        foreach (var item in PropertyInfoData)
                        {
                            item.Latitude = serviceUpdatedCustomer.Latitude;
                            item.Longitude = serviceUpdatedCustomer.Longitude;

                            await _db.SaveChangesAsync(cancellationToken);
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Unexpected Error Occured When Modify a ERP Customer Service Pack....");
                return _response.Error("Unexpected Error Occured When Modify a ERP Customer Service Pack....", AppStatusCodeError.InternalServerError500);
            }



            #region middleware
            try
            {
                using var client = new HttpClient();

                string firstApiUrl = _middlewareApiSettingsOptions.BaseUrl + "api/ChannelManager/token";

                var requestBody = new
                {
                    username = _middlewareApiSettingsOptions.UserName,
                    password = _middlewareApiSettingsOptions.Password,
                };

                var requestBodyJson = JsonConvert.SerializeObject(requestBody);
                var requestContent = new StringContent(requestBodyJson, Encoding.UTF8, "application/json");

                // Send a POST request to obtain the token
                var response = await client.PostAsync(firstApiUrl, requestContent);

                string? token = null;
                if (response.IsSuccessStatusCode)
                {
                    // Read the token from the response
                    var responseContent = await response.Content.ReadAsStringAsync();
                    var responseObject = JObject.Parse(responseContent);

                    if (responseObject != null && responseObject["token"] != null)
                    {
                        token = responseObject["token"].Value<string>();
                    }
                }

                if (!string.IsNullOrEmpty(token))
                {
                    HttpClient httpClient = new HttpClient();
                    string middlewareApiUrl = _middlewareApiSettingsOptions.BaseUrl + "api/ChannelManager/users";
                    httpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {token}");

                    var middlewareRequestBody = new
                    {
                        userCode = customer.Guid,
                        hasGeaPlatform = true
                    };

                    var middlewareRequestBodyJson = JsonConvert.SerializeObject(middlewareRequestBody);
                    requestContent = new StringContent(middlewareRequestBodyJson, Encoding.UTF8, "application/json");

                    response = await httpClient.PostAsync(middlewareApiUrl, requestContent);

                    if (response.IsSuccessStatusCode)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        Console.WriteLine("Middleware API response: " + result);
                    }
                    else
                    {
                        Console.WriteLine("Failed to call the middleware API. Status code: " + response.StatusCode);
                    }
                }
            }
            catch (HttpRequestException ex)
            {
                Console.WriteLine("An HTTP error occurred when call a Middleware APIS." + ex.Message);
                _logger.LogError(ex, "An HTTP error occurred when call a Middleware APIS.");
                return _response.Error("An HTTP error occurred when call a Middleware APIS.", AppStatusCodeError.InternalServerError500);
            }
            catch (JsonException ex)
            {
                Console.WriteLine("A JSON error occurred when call a Middleware APIS." + ex.Message);
                _logger.LogError(ex, "A JSON error occurred when call a Middleware APIS.");
                return _response.Error("A JSON error occurred when call a Middleware APIS.", AppStatusCodeError.InternalServerError500);

            }
            catch (Exception ex)
            {
                Console.WriteLine("An unexpected error occurred when call a Middleware APIS." + ex.Message);
                _logger.LogError(ex, "An unexpected error occurred when call a Middleware APIS.");
                return _response.Error("An unexpected error occurred when call a Middleware APIS.", AppStatusCodeError.InternalServerError500);
            }
            #endregion
            var UpdatedERPServicePackOut = new UpdatedERPServicePackOut()
            {
                PylonUniqueCustomerId = UserUniqueId
            };

            return _response.Success(new UpdateERPServicePackOut("Customer ServicePack Update successful.", UpdatedERPServicePackOut));

        }
    }
}
